### PR TITLE
README documentation for the allow duplicates features

### PR DESCRIPTION
**Pull request by sanjusoftware**
@NathanSweet adding documentation as well for the allow duplicate key feature

### CODE REVIEW

**Comment by NathanSweet** [comment]
Seems the PR has all the original commits?

**Comment by sanjusoftware** [comment]
yea... since you accepted my earlier pull request already, ideally when I raised a PR with diff of my master and yours, it should have given only the new README changes.. not sure why its including  everything once again!!

**Comment by NathanSweet** [comment]
I'll merge but I believe you should have merged master into your branch before creating the PR.

**Comment by sanjusoftware** [comment]
you mean your master branch!! yea, that makes complete sense.. sorry, I am sorta new to all this open source contribution stuff, so didn't need to do this much as yet.. but thanks for pointers, I'll take care of this next time :) and thx for accepting the code once again!!

**Comment by sanjusoftware** [comment]
@NathanSweet would you mind releasing this feature now, so that I can proceed using this feature in my project work as well ? :)

**Comment by NathanSweet** [comment]
No problem, happy coding!

**Comment by NathanSweet** [comment]
I did a 1.11 release. If you want it on Maven I'm afraid someone else handles that.

**Comment by sanjusoftware** [comment]
@NathanSweet thanks for release!! I understand, I can wait before it makes it to mvn. Would appreciate if you can give any idea by when do you think it can happen though?

**Comment by NathanSweet** [comment]
I don't personally use Maven and it is too much of a pain for me to deploy things there. So, never unless someone in the community does it. You might try contacting Tony, who I think has done it in the past:
https://github.com/EsotericSoftware/yamlbeans/blob/master/pom.xml#L121

**Comment by sanjusoftware** [comment]
@tchemit hi Tony, could you please help release a new version, 1.11 on mvn please? I am not able to do it myself, as I do not have sufficient right on this repository. When I try doing it from my own fork, I am getting errors in git commit that `mvn:prepare` is trying to attempt for some reason. I am still trouble shooting it, however, would be great if you can help and release this.

**Comment by sanjusoftware** [comment]
@NathanSweet for my testing through mvn, I did release the new jar version 1.11 on maven. If we get @tchemit to release a new jar 1.11, I'll take mine down (the official groupID should remain be `com.esotericsoftware.yamlbeans`, which is not the case as of now as I could not get authorization rights to post to this groupID on [mvn nexus repo](https://oss.sonatype.org)). Meanwhile, people could still use yamlbeans jar v 1.11 from mvn using [this](https://oss.sonatype.org/#nexus-search;quick~yamlbeans). Please let me know if you have any concerns.

FYI: [here](https://oss.sonatype.org/#nexus-search;quick~yamlbeans) and [here] (http://search.maven.org/#search%7Cga%7C1%7Cyamlbeans) are the new mvn jar locations

**Pull request merged**
