### PR TITLE
Added support for custom EnumSerializer classes

### PR DESCRIPTION
**Pull request by itavero**
See issue #37 for more information.

Can someone review this code and give me some feedback (or merge it if it is good enough :wink:)?
I've added a few tests to check the code.

### CODE REVIEW

**Comment by itavero** [comment]
Ping @NathanSweet

**Comment by itavero** [comment]
Perhaps it's a good idea to add a default implementation to allow for case insensitive enum values.
Something like...

```java
   public static class CaseInsensitiveEnumSerializer<T extends Enum> implements EnumSerializer<T> {

        private final Class<T> classType;

        public CaseInsensitiveEnumSerializer(final Class<T> classType) {
            this.classType = classType;
        }

        @Override
        public String write(T t) throws YamlException {
            return t.name().toLowerCase();
        }

        @Override
        public T read(String s) throws YamlException {
            return Enum.valueOf(classType, s.toUpperCase());
        }
    }
```

Note that this example relies on the fact that enum values are written in capitals, like:
```java
public enum Food {
    APPLE,
    BANANA,
    CUCUMBER,
    DONUT,
    EGG,
    FRENCH_FRIES,
    GORGONZOLA,
    HUMUS,
    IMGA_BEANS,
    JALAPENO;
}
```

**Comment by Szilard-IPSystems** [comment]
image

**Comment by Mr14huashao** [comment]
@NathanSweet 
Need this feature?
I can modify this PR if needed.

**Comment by NathanSweet** [comment]
@Mr14huashao I don't personally need it, but the idea is reasonable.

**Comment by Mr14huashao** [comment]
@NathanSweet 
This PR function has been implemented by PR 135, and it can be closed.

**Pull request closed without merging**
