### PR TITLE
Support for direct modification of a yaml document

### PR DESCRIPTION
**Pull request by ericvergnaud**
Hi,
it's great to have beans/yaml binding, but sometimes you just want to modify an existing yaml.
This PR leverages the Parser and the Emitter to that end, by introducing YamlDocument, YamlElement, YamlMapping, YamlSequence and so forth.
These reflect closely the parsed yaml with no transformation, making it easy to change values, remove entries and so forth.

### CODE REVIEW

**Comment by NathanSweet** [comment]
It looks good, thank you for your contribution!

**Comment by NathanSweet** [comment]
BTW, I'm seeing tests fail in YamlDocumentTest.

**Comment by ericvergnaud** [comment]
Not here:
Results :

Tests run: 89, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ yamlbeans ---
[INFO] Building jar: /Users/ericvergnaud/Development/yamlbeans/yamlbeans/target/yamlbeans-1.13-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ yamlbeans ---
[INFO] Installing /Users/ericvergnaud/Development/yamlbeans/yamlbeans/target/yamlbeans-1.13-SNAPSHOT.jar to /Users/ericvergnaud/.m2/repository/com/esotericsoftware/yamlbeans/yamlbeans/1.13-SNAPSHOT/yamlbeans-1.13-SNAPSHOT.jar
[INFO] Installing /Users/ericvergnaud/Development/yamlbeans/yamlbeans/pom.xml to /Users/ericvergnaud/.m2/repository/com/esotericsoftware/yamlbeans/yamlbeans/1.13-SNAPSHOT/yamlbeans-1.13-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.527 s
[INFO] Finished at: 2017-10-02T17:19:55+08:00
[INFO] Final Memory: 20M/325M
[INFO] ------------------------------------------------------------------------

Is there a CI where I can check?
If not which tests are failing?

**Comment by NathanSweet** [comment]
I see all YamlDocumentTest tests fail:

Appears to be an unexpected newline:
```
org.junit.ComparisonFailure: expected:<sequence: &anchor[
-  scalar1: value
-  scalar2: value]
> but was:<sequence: &anchor[
-  scalar1: value
-  scalar2: value
]
>
	at org.junit.Assert.assertEquals(Assert.java:99)
	at org.junit.Assert.assertEquals(Assert.java:117)
	at com.esotericsoftware.yamlbeans.document.YamlDocumentTest.testEquals(YamlDocumentTest.java:153)
	at com.esotericsoftware.yamlbeans.document.YamlDocumentTest.testThatAnchoredSequenceValueIsCopied(YamlDocumentTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by ericvergnaud** [comment]
mmm
looks like the emitter is adding a newline on your box.
I build on a mac, what about you?

**Comment by ericvergnaud** [comment]
I haven't touched the emitter
Maybe this is just revealing some historical behaviour?

**Comment by ericvergnaud** [comment]
We can get the tests to pass by just stripping the trailing newline in YamlDocumentTest:

	private void testEquals(String yaml) throws Exception {
		YamlDocument document = readDocument(yaml);
		String actual = writeDocument(document);
		if(actual.endsWith("\n"))
			actual = actual.substring(0, actual.length() - 1);
		assertEquals(yaml, actual);
	}
	
Works for me, I guess nobody cares how many newlines there are at the end of a yaml file.

**Comment by ericvergnaud** [comment]
I guess the issue could come from EmitterWriter:

	public void writeLineBreak (String data) throws IOException {
		if (data == null) data = System.getProperty("line.separator");

which makes it platform sensitive.

**Pull request merged**
